name: Test

on:
  push:

jobs:
  tests:
    name: Node build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run node tests
        run: yarn test:node
